### PR TITLE
fix: wrap extended child components

### LINKED ISSUE #790: beforeCreate hook not called sometimes
### Versions
 * vuex: 3.0.1
 * vue-test-utils: 1.0.0-beta.18
 * vue-jest: 2.6.0
 * vue-template-compiler: 2.5.16
 * vue: 2.5.16
 * jest: 23.2.0

### Reproduction link
[https://github.com/hwestphal/vue-crash-reproduce](https://github.com/hwestphal/vue-crash-reproduce)

### Steps to reproduce
1. Clone reproduction repository
2. Install dependencies using `yarn`
3. Run the unit tests using `yarn test`

### What is expected?
The unit tests should pass with no errors.

### What is actually happening?
The unit test fails because the value which is added to the component in the unit test

```
    localVue.mixin({
        beforeCreate() {
            (this as any).$content = "some value";
        },
    });
```

is accessed in the component in

```
    content(): string {
      return (this as any).$content.toUpperCase();
    }
```

which makes the test fail with

```
      TypeError: Cannot read property 'toUpperCase' of undefined
          at VueComponent.content (/home/prior/repositories/kn/vue-crash-reproduce/src/some-component.vue:13:34)
          at Watcher.get (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3140:25)
          at Watcher.evaluate (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3247:21)
          at Proxy.computedGetter (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3505:17)
          at Proxy.render (/home/prior/repositories/kn/vue-crash-reproduce/src/some-component.vue:20:153)
          at VueComponent.Vue._render (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:4542:22)
          at VueComponent.updateComponent (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:2786:21)
          at Watcher.get (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3140:25)
          at new Watcher (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3129:12)
          at mountComponent (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:2793:3)
          at VueComponent.Object.<anonymous>.Vue.$mount (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:7997:10)
          at init (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:4135:13)
          at createComponent (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:5606:9)
          at createElm (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:5553:9)
          at createChildren (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:5680:9)
          at createElm (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:5582:9)
          at VueComponent.patch [as __patch__] (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:6089:7)
          at VueComponent.Vue._update (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:2658:19)
          at VueComponent.updateComponent (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:2786:10)
          at Watcher.get (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3140:25)
          at new Watcher (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3129:12)
          at mountComponent (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:2793:3)
          at VueComponent.Object.<anonymous>.Vue.$mount (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:7997:10)
          at init (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:4135:13)
          at createComponent (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:5606:9)
          at createElm (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:5553:9)
          at VueComponent.patch [as __patch__] (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:6089:7)
          at VueComponent.Vue._update (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:2658:19)
          at VueComponent.updateComponent (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:2786:10)
          at Watcher.get (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3140:25)
          at new Watcher (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:3129:12)
          at mountComponent (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:2793:3)
          at VueComponent.Object.<anonymous>.Vue.$mount (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/vue/dist/vue.runtime.common.js:7997:10)
          at Object.mount (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/@vue/test-utils/dist/vue-test-utils.js:5940:21)
          at Object.<anonymous> (/home/prior/repositories/kn/vue-crash-reproduce/src/__tests__/test-parent-component.ts:18:32)
          at Object.asyncFn (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/jest-jasmine2/build/jasmine_async.js:82:37)
          at resolve (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/jest-jasmine2/build/queue_runner.js:52:12)
          at new Promise (<anonymous>)
          at mapper (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/jest-jasmine2/build/queue_runner.js:39:19)
          at promise.then (/home/prior/repositories/kn/vue-crash-reproduce/node_modules/jest-jasmine2/build/queue_runner.js:73:82)
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)
```

However, when deleting the access in the component, the asserts in the test:

```
    expect((wrapper.vm as any).$content).not.toBeUndefined();
    expect((wrapper.find(SomeComponent).vm as any).$content).not.toBeUndefined();
```

pass which leads to the conclusion that after the `mount(ParentComponent, { localVue })` the hook is called while it wasn't during the mount.

When removing the `Vue.extend(...)` around the `SomeComponent` in `src/some-component.vue` the error disappears and everything works fine.

---
### Hints

This issues was created as [vue#8441](https://github.com/vuejs/vue/issues/8441) was closed immediately after it was opened.

This issue might be related to [vue](https://github.com/vuejs/vue) instead. I had a look at whether [vue-jest](https://github.com/vuejs/vue-jest) could be related to this issue but it doesn't seem to be.

This issue might be the underlying issue for [vuex#1330](https://github.com/vuejs/vuex/issues/1330).

### LINKED ISSUE #819: Unit testing nested components - Child's `emitted` is undefined
### Version
1.0.0-beta.20

### Reproduction link
[https://github.com/bugsduggan/vue-test-utils-bug](https://github.com/bugsduggan/vue-test-utils-bug)

### Steps to reproduce
Clone the repo and run `npm run test:unit`. There will be one failing test indicating that the `ChildComponent`'s emitted is undefined.

### What is expected?
Having used `mount` instead of `shallowMount`, I was hoping to be able to see events that have been emitted by the `ChildComponent`.

### What is actually happening?
`ChildComponent`'s `emitted` function returns undefined.

---
I appreciate that this could be seen as testing the implementation of vue but I have 2 components that are very tightly coupled in my application and it is important for us to be able to check what events are being triggered by the child component while unit testing the parent.

If someone can help me narrow down the causes of this bug (and if it's not impossible or undesirable to fix), I would be happy to devote some hours into a pull request.

### PR DESCRIPTION
**Pull request by eddyerburgh**
Fixes https://github.com/vuejs/vue-test-utils/issues/819
Fixes #790

For localVue to work we set Vue._base to be the localVue instance, so that component constructors are created by extending the localVue constructor with component options.

This is not the case for child components already extended with Vue.extend. Because they are already Vue constructors, they aren't extended from the localVue constructor. To fix this, we need to extend each extended component manually. 

Previously we only replaced root components, with this PR we will overwrite nested extended components.

CC @lmiller1990

### CODE REVIEW

File: packages/create-instance/extend-extended-components.js [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+      !excludedComponents[c]) ||
+      stubAllComponents
+    if (shouldExtendComponent) {
+      if (logModifiedComponents) {
+        warn(
+          `an extended child component <${c}> has been modified ` +
+          `to ensure it has the correct instance properties. ` +
+          `This means it is not possible to find the component ` +
+          `with a component selector. To find the component, ` +
+          `you must stub it manually using the stubs mounting ` +
```
Comment (lmiller1990) [inline packages/create-instance/extend-extended-components.js]: couldn't `find({ name: 'foo' })` still work in this case? If so maybe that should be added here.

Comment (eddyerburgh) [reply packages/create-instance/extend-extended-components.js]: Yes it would, I'll add it.

This PR also makes your suggestion of searching by string name a lot more attractive, as it would solve this problem entirely 👍

Comment (lmiller1990) [reply packages/create-instance/extend-extended-components.js]: That would be nice 👍 Lately I (and my team) have decided on the following practice:

1. when finshing HTML elements, using the `querySelector` API
2. when finding components, use the `find(Component)` API.

which I think is the most intuitive for onboarding people new to Vue and TDD.

File: test/specs/shallow-mount.spec.js [hunk 2]
```diff
@@ -389,8 +389,7 @@ describeRunIf(process.env.TEST_ENV !== 'node', 'shallowMount', () => {
           AsyncComponent: () => import('~resources/components/component.vue')
         }
       }
-      const wrapper = shallowMount(TestComponent)
-      expect(wrapper.find({ name: 'AsyncComponent' }).exists()).to.equal(true)
```
Comment (chenxeed) [inline test/specs/shallow-mount.spec.js:393]: Hi @eddyerburgh , sorry for commenting on such an old PR.

I was wondering why is the assertion for dynamic imports on `shallowMount` were [removed](https://github.com/eddyerburgh/vue-test-utils/commit/a87d5e0561fe01fe9e9c25c85627d7c3c022a860#diff-afc732245c19e637748480fd3b06e61f)? Seems like I cannot simply handles component as dynamic import with `shallowMount` anymore :thinking:
