### PR TITLE
fix #1474: support array class binding and events binding in stubbed functional components

### LINKED ISSUE #1474: Dynamic classes not added correctly to wrapper classes when using shallowMount
### Version
1.0.0-beta.32

### Reproduction link
[https://github.com/kierans/vue-test-utils-bug](https://github.com/kierans/vue-test-utils-bug)

### Steps to reproduce
1. Create a SFC  called `Card.vue`

```
<template>
  <v-card
    outlined
    flat
  >
    <v-list-item>
      <v-list-item-avatar
          color="grey"
      />
      <v-list-item-content>
        <v-list-item-title>{{ contents.title }}</v-list-item-title>
        <v-list-item-subtitle>
          {{ contents.subtitle }}
        </v-list-item-subtitle>
      </v-list-item-content>
    </v-list-item>

    <v-card-text
        class="subtitle-1"
        v-bind:class="{
        'negative-amount': contents.amount < 0
      }"
    >
      {{ contents.amount }}
    </v-card-text>
  </v-card>
</template>

<script>
export default {
  name: "Card",
  data() {
    return {
      contents: {
        title: "Title",
        subtitle: "Subtitle",
        amount: -10
      }
    };
  }
}
</script>
```

2. Write the following test code

```
wrapper = shallowMount(Card);

const text: Wrapper<Vue> = wrapper.find(VCardText as ComponentOptions<Vue>);
expect(text.classes("negative-amount"), "Amount not marked as negative").to.be.true;
```

### What is expected?
That the classes array/string will contain the value "negative-amount"

### What is actually happening?
The classes array/string contains "[object Object]"

---

When running the app, the Card is correctly rendered with the "negative-amount" class being added.

### PR DESCRIPTION
**Pull request by palpich**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

This PR fix array class binding in stubbed functional components, because previous [PR](https://github.com/vuejs/vue-test-utils/pull/1476) add support string and object only.

Also fix events binding in stubbed functional components.

I think, best way provide all context data as the 2nd argument of h, like describe in Vue docs https://vuejs.org/v2/guide/render-function.html#Functional-Components

### CODE REVIEW

File: packages/create-instance/create-component-stubs.js [hunk 1]
```diff
@@ -134,24 +112,19 @@ export function createStubFromComponent(
     render(h, context) {
       return h(
         tagName,
-        {
-          ref: componentOptions.functional ? context.data.ref : undefined,
```
Comment (lmiller1990) [inline packages/create-instance/create-component-stubs.js:138]: are all these included in `context.data.attrs`? Curious why so much code here can be removed.

**Review by lmiller1990 — COMMENTED** [review]
Just one question

File: packages/create-instance/create-component-stubs.js (hunk 1 above)
Comment (palpich) [reply packages/create-instance/create-component-stubs.js:138]: I’ll try to explain what I’ve done —
First, I passed full data as a second argument in createElement for functional component

```
{
  // Same API as `v-bind:class`, accepting either
  // a string, object, or array of strings and objects.
  class: {
    foo: true,
    bar: false
  },
  // Same API as `v-bind:style`, accepting either
  // a string, object, or array of objects.
  style: {
    color: 'red',
    fontSize: '14px'
  },
  // Normal HTML attributes
  attrs: {
    id: 'foo'
  },
  // Component props
  props: {
    myProp: 'bar'
  },
  // DOM properties
  domProps: {
    innerHTML: 'baz'
  },
  // Event handlers are nested under `on`, though
  // modifiers such as in `v-on:keyup.enter` are not
  // supported. You'll have to manually check the
  // keyCode in the handler instead.
  on: {
    click: this.clickHandler
  },
  // For components only. Allows you to listen to
  // native events, rather than events emitted from
  // the component using `vm.$emit`.
  nativeOn: {
    click: this.nativeClickHandler
  },
  // Custom directives. Note that the `binding`'s
  // `oldValue` cannot be set, as Vue keeps track
  // of it for you.
  directives: [
    {
      name: 'my-custom-directive',
      value: '2',
      expression: '1 + 1',
      arg: 'foo',
      modifiers: {
        bar: true
      }
    }
  ],
  // Scoped slots in the form of
  // { name: props => VNode | Array<VNode> }
  scopedSlots: {
    default: props => createElement('span', props.text)
  },
  // The name of the slot, if this component is the
  // child of another component
  slot: 'name-of-slot',
  // Other special top-level properties
  key: 'myKey',
  ref: 'myRef',
  // If you are applying the same ref name to multiple
  // elements in the render function. This will make `$refs.myRef` become an
  // array
  refInFor: true
}
```

because some property had been missed — `props, on (so events don't work), nativeOn, directives, scopedSlots, slot, key, ref, refInFor`. We can get all property from `context.data`.
[Data-Object docs](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth)

`class, staticClass and style` property also forwarded in Data-Object. As we don't mix any class or styles, we don't need to do any preparation, because Vue processes them independently, one of accepted type — array, object or string.

In fact, we create HOC, which proxies all data:

```
return createElement(
      SomeComponent,
      context.data,
      context.children
    )
```

 [example from here](https://vuejs.org/v2/guide/render-function.html#Passing-Attributes-and-Events-to-Child-Elements-Components)

Also, I assign `context.props` and `context.data.attrs` in to Data-Object `attrs`, because Vue not rendered entries from `context.props` in html, if key of entries was extracted.

image

image

It standard behavior for Vue, but fix it do break current behavior vue-test-utils.

Comment (lmiller1990) [reply packages/create-instance/create-component-stubs.js:138]: This is my main concern - since we are in 1.0 now, this is a *breaking* change for a lot of users. But it does make sense we have feature parity with Vue.

Maybe @afontcu has some opinion? My guess is this will only impact snapshots users - so if we make it clear they need to update their snapshots, maybe it's okay. 🤔 

At this point I am not sure about the trade-off between correctness and stability.

This would need to be a minor version bump at the very least.

Comment (palpich) [reply packages/create-instance/create-component-stubs.js:138]: I agree that the better way is to request for comments of other developers and not to push breaking changes now.

Therefore, I kept the standard behavior VTU and only add support array class binding and events binding into stubbed functional components.

Comment (lmiller1990) [reply packages/create-instance/create-component-stubs.js:138]: Right I think I misunderstood - just to clarify, this change only impacts stubbed functional components (and no change to non stubbed components, and regular stubbed components?)

If that is the case this probably isn't as big a change as I thought, and we could just make this a minor version release. Can you please clarify?

Comment (palpich) [reply packages/create-instance/create-component-stubs.js:138]: Yes, this change only impacts stubbed functional components. 

I was planning this as a MINOR update, maybe even as a PATCH.

Comment (lmiller1990) [reply packages/create-instance/create-component-stubs.js:138]: I think this is fine. I will make this a minor release.
