### PR TITLE
fix: handle null in set data

### LINKED ISSUE #888: setData() | right-hand side of 'in' should be an object, got null
### Version
1.0.0-beta.22

### Reproduction link
[https://github.com/reginsmol/test-utils-setdata-reproduction](https://github.com/reginsmol/test-utils-setdata-reproduction)

### Steps to reproduce
1. npm install 
2. npm run dev
3. npm run unit

### What is expected?
setData() should set the data property to the new value passed in.

### What is actually happening?
Throws errors:
 ```
TypeError: Cannot use 'in' operator to search for 'key' in null
            at VueComponent.set [as $set] (webpack:///node_modules/vue/dist/vue.esm.js:1035:0 <- index.js:1195:11)
            at webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1152:0 <- index.js:12632:10
            at Array.forEach (<anonymous>)
            at recursivelySetData (webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1147:0 <- index.js:12627:20)
            at webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1150:0 <- index.js:12630:7
            at Array.forEach (<anonymous>)
            at recursivelySetData (webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1147:0 <- index.js:12627:20)
            at VueWrapper.setData (webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1644:0 <- index.js:13124:3)
            at Context.<anonymous> (webpack:///test/unit/specs/HelloWorld.spec.js:9:12 <- index.js:11445:13)

right-hand side of 'in' should be an object, got undefined
        set@webpack:///node_modules/vue/dist/vue.esm.js:1035:0 <- index.js:1195:1
        recursivelySetData/<@webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1152:0 <- index.js:12640:7
        recursivelySetData@webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1147:0 <- index.js:12635:3
        recursivelySetData/<@webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1150:0 <- index.js:12638:7
        recursivelySetData@webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1147:0 <- index.js:12635:3
        setData@webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:1644:0 <- index.js:13132:3
        @webpack:///test/unit/specs/HelloWorld.spec.js:18:4 <- index.js:11453:5
```

### PR DESCRIPTION
**Pull request by eddyerburgh**
- Handle data set from null to an object

Closes #888

### CODE REVIEW

File: packages/test-utils/src/recursively-set-data.js [hunk 1]
```diff
@@ -1,10 +1,12 @@
...
-    const val = obj[key]
-    if (isPlainObject(val)) {
-      recursivelySetData(vm, target[key], val)
+export function recursivelySetData (vm, target, data) {
+  Object.keys(data).forEach(key => {
+    const val = data[key]
+    const targetVal = target[key]
+
+    if (isPlainObject(val) && isPlainObject(targetVal)) {
+      recursivelySetData(vm, targetVal, val)
```
Comment (lmiller1990) [inline packages/test-utils/src/recursively-set-data.js:9]: It seems like you just add a check to see if `targetVal` is a plain object, why does this solve the problem?

Comment (eddyerburgh) [reply packages/test-utils/src/recursively-set-data.js:9]: null isn't a plain object, so we call Vue.set on the target property, rather than recursively setting.
