### PR TITLE
fix: improve slots option

### LINKED ISSUE #793: $parent of a child component defined on a slot, reference to itself
### Version
1.0.0-beta.20

### Reproduction link
[https://codesandbox.io/s/wqo716rm55](https://codesandbox.io/s/wqo716rm55)

### Steps to reproduce
Run the test written on sandbox

### What is expected?
It should work as works on the browser so `this.$parent` should return the parent of the component and not itself.

### What is actually happening?
I have a scenario similar to what I reproduce in the sandbox. I have a few components that are inserted on the default slot of a "wrapper" component, each of these components are registered on the parent when are mounted using a method on the parent `this.$parent.register`.
All work on the browser but when I tried to test the `this.$parent` of the child component refers to itself and the test fails because it doesn't find the register method.

---
For example If I change `this.$parent` by `this.$parent.$parent` all works.

### PR DESCRIPTION
**Pull request by 38elements**
This resolves #793.

### CODE REVIEW

File: packages/create-instance/create-slot-vnodes.js [hunk 1]
```diff
@@ -18,7 +19,17 @@ function createVNodesForSlot (
   const el =
     typeof slotValue === 'string' ? compileToFunctions(slotValue) : slotValue
 
-  const vnode = h(el)
+  let vnode = h(el)
+  if (typeof slotValue === 'string') {
+    const vue = new Vue()
```
Comment (eddyerburgh) [inline packages/create-instance/create-slot-vnodes.js]: I think this would be a problem if you mount a component that uses localVue and the slot component accesses a property that is only added to the localVue prototype, can you write a test to check?

**Comment by 38elements** [comment]
This case does not work.
I will make another issue.

```js
slots: {
  default: '<div><component-with-parent-name /></div>'
}
```

File: packages/create-instance/create-slot-vnodes.js (hunk 1 above)
Comment (38elements) [reply packages/create-instance/create-slot-vnodes.js]: I will add test.

Comment (38elements) [reply packages/create-instance/create-slot-vnodes.js]: Yes, it is.
Changing `localVue.prototype`, this does not work.
Using `vm._renderProxy` is correct if possible.
I will add test for changing `localVue.prototype`.

**Comment by 38elements** [comment]
I will add test for changing `localVue.prototype`.
I think this change is temporary solution.
I will seek another solution.

**Comment by 38elements** [comment]
I added a test for changing `localVue.prototype`.
I think this change is temporary solution.
I will seek another solution.

File: packages/create-instance/create-slot-vnodes.js [hunk 2]
```diff
@@ -22,6 +23,12 @@ function createVNodesForSlot (
   let vnode = h(el)
   if (typeof slotValue === 'string') {
     const vue = new Vue()
+    const _vue = new _Vue()
```
Comment (eddyerburgh) [inline packages/create-instance/create-slot-vnodes.js]: why not just use the _vue.renderProxy rather than mixing both?

Comment (38elements) [reply packages/create-instance/create-slot-vnodes.js]: Since it raises an error.

**Comment by 38elements** [comment]
I will send  the pull request for another solution within 3 days.

**Comment by 38elements** [comment]
@eddyerburgh 
I sent the pull request for another solution.
It is #821.

**Comment by 38elements** [comment]
I think #821 is better than this.

File: packages/create-instance/create-slot-vnodes.js [hunk 3]
```diff
@@ -18,22 +20,41 @@ function createVNodesForSlot (
...
     typeof slotValue === 'string' ? compileToFunctions(slotValue) : slotValue
 
-  const vnode = h(el)
+  let vnode = h(el)
+  if (typeof slotValue === 'string') {
+    const vue = new Vue()
+    const _vue = new _Vue()
+    for (const key in _vue._renderProxy) {
+      if (!(vue._renderProxy[key])) {
+        vue._renderProxy[key] = _vue._renderProxy[key]
```
Comment (eddyerburgh) [inline packages/create-instance/create-slot-vnodes.js]: Why not always use _vue.renderProxy?

File: packages/create-instance/create-slot-vnodes.js [hunk 4]
```diff
@@ -18,22 +20,41 @@ function createVNodesForSlot (
...
+      }
+    }
+    try {
+      // $FlowIgnore
+      vnode = el.render.call(vue._renderProxy, h)
```
Comment (eddyerburgh) [inline packages/create-instance/create-slot-vnodes.js]: Do components without a render function work here?

For example:

```js
mount(TestComponent,{
  slots: { default: {
    template: '<div />'
  }}
})
```

Can you add a test for this kind of slot

**Comment by eddyerburgh** [comment]
Could you also include a fix for #828? Your previous PR would have solved this (adding a parent div to template strings, and using the child value)

**Comment by 38elements** [comment]
I will try to add it.

File: packages/create-instance/create-slot-vnodes.js (hunk 3 above)
Comment (38elements) [reply packages/create-instance/create-slot-vnodes.js]: ~~When `vue.renderProxy` is used, it raises an error.~~ 
When `_vue.renderProxy` is used, it raises an error.

```
TypeError: Cannot read property 'Ctor' of undefined
```

Comment (eddyerburgh) [reply packages/create-instance/create-slot-vnodes.js]: Do you mean when `_vue.renderProxy` is used?

Comment (38elements) [reply packages/create-instance/create-slot-vnodes.js]: It does not raise the error.

Comment (38elements) [reply packages/create-instance/create-slot-vnodes.js]: I am sorry.
Yes, I do.

**Comment by 38elements** [comment]
@eddyerburgh 
I changed this.
IMHO,
Since #828 does not uses slots, I think this pull request is not related it.
I do not know #734 well.
It seems that this might be related #734.
I think this might resolve #734.

**Comment by eddyerburgh** [comment]
Ok sounds good. Can you add the tests from #734 to verify that this PR solves the issue?

**Comment by 38elements** [comment]
@eddyerburgh 
I added a test for #734.

**Review by eddyerburgh — APPROVED** [review]

**Comment by eddyerburgh** [comment]
Nice work, thanks :)

**Comment by 38elements** [comment]
@eddyerburgh 
I am sorry.
#734 is not resolved.

**Comment by 38elements** [comment]
@eddyerburgh 
Thank you for reviewing.
I am sorry.
The test for #734 which is added at this pull request is incorrect.
#734 is not resolved.
I sent a pull request #847.
