### PR TITLE
fix(slots): functional component text slots

### LINKED ISSUE #732: Slots with text contents are not properly resolved in functional components.
### Version
1.0.0-beta.19

### Reproduction link
[https://codesandbox.io/s/ollqlyxv2y](https://codesandbox.io/s/ollqlyxv2y)

### Steps to reproduce
In beta.19, template component slots can be filled with strings easily. But functional components still cannot.

* Create a functional component with a slot (can be default or named)
* Create a test suite which fills the slot with a simple string
* See the `<div></div>` problem again.

### What is expected?
The slot should be properly filled with the string

### What is actually happening?
The `<div></div>` problem is occuring again

Related: #718, #707, #711

### PR DESCRIPTION
**Pull request by TheAlexLichter**
Resolves #732

### CODE REVIEW

File: packages/server-test-utils/dist/vue-server-test-utils.js [hunk 1]
```diff
@@ -19,14 +19,12 @@ function createVNodesForSlot (
   slotValue,
   name
 ) {
-  if (typeof slotValue === 'string' &&
-  !startsWithTag(slotValue)) {
+  if (typeof slotValue === 'string' && !startsWithTag(slotValue)) {
```
Comment (jacekkarczmarczyk) [inline packages/server-test-utils/dist/vue-server-test-utils.js]: These changes are not related to the issue, files are automatically updated on `yarn test` or something, but they shouldn't be included in the PR

File: packages/create-instance/create-functional-component.js [hunk 2]
```diff
@@ -4,35 +4,35 @@ import { compileToFunctions } from 'vue-template-compiler'
 import { throwError } from 'shared/util'
 import { validateSlots } from './validate-slots'
 
-function createFunctionalSlots (slots = {}, h) {
-  if (Array.isArray(slots.default)) {
-    return slots.default.map(h)
-  }
+function startsWithTag (str) {
```
Comment (jacekkarczmarczyk) [inline packages/create-instance/create-functional-component.js]: `startsWithTag` is also defined in add-slots.js, I guess it could be extracted to some helper

File: packages/test-utils/dist/vue-test-utils.js [hunk 3]
```diff
@@ -17,7 +17,10 @@ function warn (msg) {
 
 var camelizeRE = /-(\w)/g;
 var camelize = function (str) {
-  var camelizedStr = str.replace(camelizeRE, function (_, c) { return c ? c.toUpperCase() : ''; });
```
Comment (jacekkarczmarczyk) [inline packages/test-utils/dist/vue-test-utils.js]: These changes are not related to the issue, files are automatically updated on yarn test or something, but they shouldn't be included in the PR

File: packages/server-test-utils/dist/vue-server-test-utils.js (hunk 1 above)
Comment (TheAlexLichter) [reply packages/server-test-utils/dist/vue-server-test-utils.js]: Whoops! Thanks :relaxed:

File: packages/create-instance/create-functional-component.js (hunk 2 above)
Comment (TheAlexLichter) [reply packages/create-instance/create-functional-component.js]: Right! Actually, we could use the `add-slots` files as well.

Let me refactor it :+1:

**Comment by TheAlexLichter** [comment]
@jacekkarczmarczyk I've refactored it. But I've encountered a strange behavior:

Currently, the implementation uses the `createFunctionalSlotVNodes` function. This is just a "redirect" ([see here](https://github.com/vuejs/vue-test-utils/pull/733/commits/31a3d0bf110f6d52e803a7b57627f87fa1a8d475#diff-2aef106d4e1902310b282815a009490aR41)):

```
export function createFunctionalSlotVNodes (h, slots = {}) {
  return createSlotVNodes(h, slots)
}
```

However, if I replace all calls with the `createSlotVNodes` function, karma throws several errors. 

Can't explain the behavior to me:man_shrugging: 
Do you have any idea?

EDIT: And flow is failing because of types

**Comment by jacekkarczmarczyk** [comment]
You've overwritten https://github.com/vuejs/vue-test-utils/commit/bc736fb6431e54ba5a9cf7908044e5c71234facc ...

**Comment by TheAlexLichter** [comment]
@jacekkarczmarczyk Dang! :roll_eyes:  Still too early for me :see_no_evil: 

Should look better now...

**Comment by TheAlexLichter** [comment]
Okay, one more try. I think I got it now. Test running locally and flow doesn't complain anymore :yum:

File: packages/create-instance/add-slots.js [hunk 4]
```diff
@@ -30,12 +30,17 @@ export function createSlotVNodes (
...
       return acc.concat(nodes)
-    } else {
-      return acc.concat(createVNodesForSlot(h, content, key))
     }
+
+    return acc.concat(createVNodesForSlot(h, content, key))
   }, [])
 }
+
+export function createFunctionalSlotVNodes (
```
Comment (eddyerburgh) [inline packages/create-instance/add-slots.js]: No need to add this function, we can just use `createSlotVNodes`

File: packages/create-instance/add-slots.js [hunk 5]
```diff
@@ -6,7 +6,7 @@ function startsWithTag (str) {
   return str && str.trim()[0] === '<'
 }
 
-function createVNodesForSlot (
+export function createVNodesForSlot (
```
Comment (eddyerburgh) [inline packages/create-instance/add-slots.js]: I don't think we need to export

File: packages/create-instance/create-functional-component.js [hunk 6]
```diff
@@ -1,39 +1,8 @@
...
-          ? compileToFunctions(slots[slotType])
-          : slots[slotType]
-      const slot = h(component)
-      slot.data.slot = slotType
-      children.push(slot)
-    }
-  })
-  return children
-}
+import { createFunctionalSlotVNodes } from './add-slots'
```
Comment (eddyerburgh) [inline packages/create-instance/create-functional-component.js]: Can you use createSlotVNodes instead?

**Review by eddyerburgh — CHANGES_REQUESTED** [review]
Thanks for the PR, looks good although I think we can use the existing `createSlotVnodes` function instead of the new function

edit: I've just seen your comments about karma. Can you post the errors?

File: packages/create-instance/create-functional-component.js (hunk 6 above)
Comment (TheAlexLichter) [reply packages/create-instance/create-functional-component.js]: I tried this, but it gave me some strange errors.

See https://github.com/vuejs/vue-test-utils/pull/733#issuecomment-397980897

Comment (TheAlexLichter) [reply packages/create-instance/create-functional-component.js]: Update: Looks like this had sth. to do with wrong types. It works fine right now :man_shrugging:

**Comment by TheAlexLichter** [comment]
@eddyerburgh I think those were related to flow issues as everything works fine now :relaxed: 

I've updated the PR. Hope the tests will pass like they do locally :+1:

**Review by eddyerburgh — APPROVED** [review]
Great, thanks 👍 

A PR that removes more code than it adds, AND fixes a bug is always good!

**Comment by TheAlexLichter** [comment]
@eddyerburgh  You are welcome :relaxed: 

Cannot agree more on that! :speak_no_evil:

**Comment by TheAlexLichter** [comment]
@eddyerburgh Do you know when the change will be released? :)

**Comment by eddyerburgh** [comment]
I'll release within a week
