### PR TITLE
fix #1793 (Add WrapperArray#exists docs)

### LINKED ISSUE #1793: WrapperArray#exists is not documented
### Version
1.1.3

### Reproduction link
[https://vue-test-utils.vuejs.org/api/wrapper-array/](https://vue-test-utils.vuejs.org/api/wrapper-array/)

### Steps to reproduce
1. https://vue-test-utils.vuejs.org/api/wrapper-array/
1. Observe there's no entry for `exists`
1. Visit https://github.com/vuejs/vue-test-utils/blob/v1.1.3/packages/test-utils/src/wrapper-array.js#L60-L62
1. Observe the method does indeed exist

### What is expected?
That it be documented :)

### What is actually happening?
It's not documented.

### PR DESCRIPTION
**Pull request by markrian**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: docs

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

### CODE REVIEW

File: packages/test-utils/src/wrapper.js [hunk 1]
```diff
@@ -208,7 +208,7 @@ export default class Wrapper implements BaseWrapper {
   }
 
   /**
-   * Utility to check wrapper exists. Returns true as Wrapper always exists
+   * Utility to check wrapper exists.
```
Comment (markrian) [inline packages/test-utils/src/wrapper.js:211]: This appeared to be an outdated comment for the `exists` method, since it a Wrapper doesn't always exist, since it can return `false` :slightly_smiling_face:

**Comment by markrian** [comment]
@afontcu Would you review this, please?

File: packages/test-utils/src/wrapper.js (hunk 1 above)
Comment (afontcu) [reply packages/test-utils/src/wrapper.js:211]: indeed!

**Review by afontcu — APPROVED** [review]
looks good! 🚀
